apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    tier: frontend
    component: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  #these labels are replicaset lables
  labels:
    project: roboshop
    tier: frontend
    component: frontend
spec:
  replicas: 1
  selector: 
    # using these labels replicaset selects the pod
      matchLabels:
        project: roboshop
        tier: frontend
        component: frontend
  template:
    metadata:
      labels:
        project: roboshop
        tier: frontend
        component: frontend
    spec:
      containers:
      - name: frontend 
        image: varunkumarpinnam/frontend:1.2.0
        imagePullPolicy: Always # safe to pull everytime, there may be images with same version rebuilt and pushed
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "150Mi"
            cpu: "150m"        
        readinessProbe:
          tcpSocket:
            port: 80
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 2
          periodSeconds: 10
        envFrom:
        - configMapRef:
           name: frontend
      
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
  labels:
      project: roboshop
      tier: frontend
      component: frontend
spec:
  type: LoadBalancer
  selector:
  # labels are used as selectors
    project: roboshop
    tier: frontend
    component: frontend
  ports:
  - protocol: TCP
    port: 80 #servie port
    targetPort: 80 # container port

      